# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
    groups:
      version-updates:
        applies-to: version-updates
      security-updates:
        applies-to: security-updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      security:
        applies-to: security-updates
      normal:
        applies-to: version-updates
