name: Setup CI context
description: Sets up repo and Node context and installs packages

inputs:
  branch:
    type: string
    default: next
    description: The branch to fetch
  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  node-version:
    type: number
    default: 20
    description: The Node version to use

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - run: npm ci
