name: '📃 Documentation Issue'
description: Report an issue with Mithril.js's documentation
assignees: dead-claudia
labels:
- 'Area: Documentation'
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Offending URL
    description: Provide a link to the page with the issue
    placeholder: https://mithril.js.org/
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue description
    description: What is the precise issue with it. Please be specific.
  validations:
    required: true
