name: Ping triage on issue create

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment ${{ github.event.issue.url }} --body '@MithrilJS/triage Please take a look.'
        env:
          GITHUB_TOKEN: ${{ github.token }}
