name: Ping triage on issue create
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  notify:
    uses: ./.github/workflows/_post-comment.yml
    with:
      url: ${{ github.event.issue.url }}
      message: '@MithrilJS/triage Please take a look.'
