name: lint-js

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/setup
    - run: npm run lint:js
