name: lint-docs

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  lint-docs:
    # https://github.com/MithrilJS/mithril.js/issues/2898
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/setup
      with: {branch: next}
    - run: npm run lint:docs
