name: Warn on opening a PR to `release`
on:
  pull_request_target:
    types: [opened]
    branches: [release]
permissions:
  issues: write
jobs:
  comment:
    # Don't auto-close actual release PRs
    if: ${{github.actor != 'JAForbes' || !contains(github.event.issue.title, 'Release - v')}}
    uses: MithrilJS/infra/.github/workflows/reject-pr.yml@main
    secrets: inherit
