# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test-js

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  test-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
        - 16
        - 18
        - 20
        - 22
    steps:
    - uses: ./.github/actions/setup
      with:
        branch: next
        node-version: ${{ matrix.node-version }}
    - run: npm run test:js
